### ISSUE TITLE
Allow multiple account registration options to be used for score calculations 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-backend#93]
### Overview 

We only conisder one category, currently affiliations, to determine the groupings that enter the plurality score calculation. However, we might want to use or not use any number of account registrations options to enter the plurality score calculation.

**Comment by diegoalzate** [comment]
## objectives
- have affiliations related to events
- have multiple affiliations per user

### important use cases
- events have to be able to get a lists of groups
- events have to be able to get a couple lists of groups (different levels of groups)
- users have to be able to link to the groups

### how?
- create a group_categories table that will have an eventID
- add group_category_id and event_id to groups to relate a group to one event and one group_category

### changes to dynamic event form
- for each category that is related to an event there will be a Select with all related groups. So it will not be defined by a registrationField, we might want to rethink this or add more thought into how to integrate it with registrationField because that way it can be ordered somehow. With the simplest solution we would have it at the end of the form. 

- when you choose a group from the groups that are related to an event, the current users_to_groups table is still compatible so no changes there

**Comment by MartinBenediktBusch** [comment]
This would be a suggestion for the modified groups table which includes a new `groupsCategoryId` field with a many to many relationship: 

```
export const groups = pgTable('groups', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 256 }).notNull(),
  description: varchar('description', { length: 256 }),
  groupCategoryId: uuid('group_category_id').references(() => group_categories.id).notNull(), 
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const groupsRelations = relations(groups, ({ many }) => ({
  usersToGroups: many(usersToGroups),
  groupCategories: many(groupsCategories),
}));

export type Group = typeof groups.$inferSelect;
```

**Comment by diegoalzate** [comment]
![image](https://github.com/lexicongovernance/pluraltools-backend/assets/22416585/d0072591-efa6-49ff-98cd-41701fffcadc)
